export const PRODUCTS = [
  {
    id: "tshirt-1",
    name: "Let's Go Boys T-Shirt White",
    price: "LKR 850",
    image: "/product9.png",
    badge: "COD",
    description: "Soft premium cotton tee designed for everyday play.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-2",
    name: "Little Tiger Boys T-Shirt Green" ,
    price: "LKR 850",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-3",
    name: "Torido Boys T-Shirt Maroon",
    price: "LKR 850",
    image: "/product3.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-4",
    name: "Let's Go Boys T-Shirt Black Gray",
    price: "LKR 850",
    image: "/product4.png",
    badge: "COD",
    description: "Soft premium cotton tee designed for everyday play.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-5",
    name: "Space Explorer Boys T-Shirt Gray",
    price: "LKR 850",
    image: "/product5.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-6",
    name: "Little Jumbo Boys T-Shirt Black",
    price: "LKR 850",
    image: "/product6.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-7",
    name: "Torido Boys T-Shirt White",
    price: "LKR 850",
    image: "/product8.png",
    badge: "COD",
    description: "Soft premium cotton tee designed for everyday play.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-8",
    name: "Torido Boys T-Shirt Black",
    price: "LKR 850",
    image: "/product7.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
 
];

export const BEST_SELLERS = [
  {
    id: "best-1",
    name: "Dino Classic Tee",
    price: "Rs 2,450",
    image: "/product1.png",
    badge: "BEST",
    description: "A bestselling cotton tee designed for everyday wear.",
    sizes: ["2Y", "4Y", "6Y", "8Y"],
  },
  {
    id: "best-2",
    name: "Dino Classic Tee",
    price: "Rs 1,450",
    image: "/product2.png",
    badge: "BEST",
    description: "A bestselling cotton tee designed for everyday wear.",
    sizes: ["2Y", "4Y", "6Y", "8Y"],
  },
  {
    id: "best-1",
    name: "Dino Classic Tee",
    price: "Rs 2,450",
    image: "/product3.png",
    badge: "BEST",
    description: "A bestselling cotton tee designed for everyday wear.",
    sizes: ["2Y", "4Y", "6Y", "8Y"],
  },
  {
    id: "best-1",
    name: "Dino Classic Tee",
    price: "Rs 2,450",
    image: "/product4.png",
    badge: "BEST",
    description: "A bestselling cotton tee designed for everyday wear.",
    sizes: ["2Y", "4Y", "6Y", "8Y"],
  },
  {
    id: "best-1",
    name: "Dino Classic Tee",
    price: "Rs 2,450",
    image: "/product5.png",
    badge: "BEST",
    description: "A bestselling cotton tee designed for everyday wear.",
    sizes: ["2Y", "4Y", "6Y", "8Y"],
  },
];
