export const PRODUCTS = [
  {
    id: "tshirt-1",
    name: "Dino Smile Tee",
    price: "Rs 2,450",
    image: "/product1.jpg",
    badge: "COD",
    description: "Soft premium cotton tee designed for everyday play.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-2",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-3",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-4",
    name: "Dino Smile Tee",
    price: "Rs 2,450",
    image: "/product1.jpg",
    badge: "COD",
    description: "Soft premium cotton tee designed for everyday play.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-5",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-6",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-7",
    name: "Dino Smile Tee",
    price: "Rs 2,450",
    image: "/product1.jpg",
    badge: "COD",
    description: "Soft premium cotton tee designed for everyday play.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-8",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-9",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
];

export const BEST_SELLERS = [
  {
    id: "best-1",
    name: "Dino Classic Tee",
    price: "Rs 2,450",
    image: "/product1.jpg",
    badge: "BEST",
    description: "A bestselling cotton tee designed for everyday wear.",
    sizes: ["2Y", "4Y", "6Y", "8Y"],
  },
  {
    id: "best-2",
    name: "Dino Classic Tee",
    price: "Rs 1,450",
    image: "/product1.jpg",
    badge: "BEST",
    description: "A bestselling cotton tee designed for everyday wear.",
    sizes: ["2Y", "4Y", "6Y", "8Y"],
  },
];