export const PRODUCTS = [
  {
    id: "dino-smile",
    name: "Dino Smile Tee",
    price: "Rs 2,450",
    image: "/product1.jpg",
    badge: "COD",
    description: "Soft premium cotton tee designed for everyday play.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "unicorn-dreams",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "unicorn-dreams-2",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-4",
    name: "Dino Smile Tee",
    price: "Rs 2,450",
    image: "/product1.jpg",
    badge: "COD",
    description: "Soft premium cotton tee designed for everyday play.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-5",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-6",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-7",
    name: "Dino Smile Tee",
    price: "Rs 2,450",
    image: "/product1.jpg",
    badge: "COD",
    description: "Soft premium cotton tee designed for everyday play.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-8",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
  {
    id: "tshirt-9",
    name: "Unicorn Dreams Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "COD",
    description: "Comfortable printed tee with a playful unicorn design.",
    sizes: ["S", "M", "L"],
  },
];

export const BEST_SELLERS = [
  {
    id: "best-1",
    name: "Dino Classic Tee",
    price: "Rs 2,450",
    image: "/product1.jpg",
    badge: "BEST",
  },
  {
    id: "best-2",
    name: "Unicorn Spark Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "BEST",
  },
  {
    id: "best-3",
    name: "Explorer Print Tee",
    price: "Rs 2,350",
    image: "/product1.jpg",
    badge: "BEST",
  },
  {
    id: "best-4",
    name: "Dino Classic Tee",
    price: "Rs 2,450",
    image: "/product1.jpg",
    badge: "BEST",
  },
  {
    id: "best-5",
    name: "Unicorn Spark Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "BEST",
  },
  {
    id: "best-6",
    name: "Explorer Print Tee",
    price: "Rs 2,350",
    image: "/product1.jpg",
    badge: "BEST",
  },
  {
    id: "best-7",
    name: "Dino Classic Tee",
    price: "Rs 2,450",
    image: "/product1.jpg",
    badge: "BEST",
  },
  {
    id: "best-8",
    name: "Unicorn Spark Tee",
    price: "Rs 2,300",
    image: "/product2.png",
    badge: "BEST",
  },
  {
    id: "best-9",
    name: "Explorer Print Tee",
    price: "Rs 2,350",
    image: "/product1.jpg",
    badge: "BEST",
  },
];